### ISSUE TITLE
why cant i find lamar jackson

### ISSUE THREAD

**Issue by manbradcalf** [manbradcalf/nfl-player-stats-node#4]
This returns an error
```
TypeError: Cannot read property 'forEach' of undefined
    at Object.mapResultsForTable (/Users/benmedcalf/ff2020/dist/js/mutators.js:22:16)
    at /Users/benmedcalf/ff2020/dist/app.js:35:44
    at Generator.next (<anonymous>)
    at fulfilled (/Users/benmedcalf/ff2020/dist/app.js:5:58)
```

<img width="573" alt="Screen Shot 2020-08-23 at 11 27 22 PM" src="https://user-images.githubusercontent.com/11594171/91000903-3f6b2e80-e598-11ea-8930-bc4ca6fd9cdb.png">

**Comment by manbradcalf** [comment]
this works in the db now ... 

match (p)-[r1]-(s1:NFLStatisticalSeason{name:2019})
where r1.rushingYards > 1000 and p.position = "TQB"
return p
